okta:
  oauth2:
    issuer: https://dev-96775597.okta.com/oauth2/default
    client-id: 0oanu1pu6iK9hDleZ5d7
    client-secret: QfEjFnyIFtZ8L4mJD2s4FzRPpPHXfXg0BhmSLxq2yV_B6yy5FF5RXNHZlNmnrjx1
    scopes: openid,profile,email,offline_access

spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            scope: openid, profile, email
        provider:
          okta:
            user-name-attribute: email